export const PRODUCT_LIST_DATA = [
  {
    id: "1",
    name: "Flash Sale - 99k/ 01kg Nho đen không hạt Mỹ",
    images: [
      "/assets/images/products/nhodenkhonghat/img1.webp",
      "/assets/images/products/nhodenkhonghat/img2.webp",
      "/assets/images/products/nhodenkhonghat/img3.webp",
      "/assets/images/products/nhodenkhonghat/img4.webp",
      "/assets/images/products/nhodenkhonghat/img5.webp",
    ],
    code: "web2200160-1",
    vendor: "Mỹ",
    originalPrice: 123,
    status: "còn hàng | hết hàng",
    info: [
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
      },
    ],
    description: "",
  },
  {
    id: "2",
    name: "Flash Sale - 99k/ 01kg Nho đen không hạt Mỹ",
    images: [
      "/assets/images/products/nhodenkhonghat/img1.webp",
      "/assets/images/products/nhodenkhonghat/img2.webp",
      "/assets/images/products/nhodenkhonghat/img3.webp",
      "/assets/images/products/nhodenkhonghat/img4.webp",
      "/assets/images/products/nhodenkhonghat/img5.webp",
    ],
    code: "web2200160-1",
    vendor: "Mỹ",

    status: "còn hàng | hết hàng",
    info: [
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
    ],
    description: "",
  },
  {
    id: "1",
    name: "Flash Sale - 99k/ 01kg Nho đen không hạt Mỹ",
    images: [
      "/assets/images/products/nhodenkhonghat/img1.webp",
      "/assets/images/products/nhodenkhonghat/img2.webp",
      "/assets/images/products/nhodenkhonghat/img3.webp",
      "/assets/images/products/nhodenkhonghat/img4.webp",
      "/assets/images/products/nhodenkhonghat/img5.webp",
    ],
    code: "web2200160-1",
    vendor: "Mỹ",

    status: "còn hàng | hết hàng",
    info: [
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
    ],
    description: "",
  },
  {
    id: "1",
    name: "Flash Sale - 99k/ 01kg Nho đen không hạt Mỹ",
    images: [
      "/assets/images/products/nhodenkhonghat/img1.webp",
      "/assets/images/products/nhodenkhonghat/img2.webp",
      "/assets/images/products/nhodenkhonghat/img3.webp",
      "/assets/images/products/nhodenkhonghat/img4.webp",
      "/assets/images/products/nhodenkhonghat/img5.webp",
    ],
    code: "web2200160-1",
    vendor: "Mỹ",

    status: "còn hàng | hết hàng",
    info: [
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
    ],
    description: "",
  },
  {
    id: "1",
    name: "Flash Sale - 99k/ 01kg Nho đen không hạt Mỹ",
    images: [
      "/assets/images/products/nhodenkhonghat/img1.webp",
      "/assets/images/products/nhodenkhonghat/img2.webp",
      "/assets/images/products/nhodenkhonghat/img3.webp",
      "/assets/images/products/nhodenkhonghat/img4.webp",
      "/assets/images/products/nhodenkhonghat/img5.webp",
    ],
    code: "web2200160-1",
    vendor: "Mỹ",

    status: "còn hàng | hết hàng",
    info: [
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
    ],
    description: "",
  },
  {
    id: "1",
    name: "Flash Sale - 99k/ 01kg Nho đen không hạt Mỹ",
    images: [
      "/assets/images/products/nhodenkhonghat/img1.webp",
      "/assets/images/products/nhodenkhonghat/img2.webp",
      "/assets/images/products/nhodenkhonghat/img3.webp",
      "/assets/images/products/nhodenkhonghat/img4.webp",
      "/assets/images/products/nhodenkhonghat/img5.webp",
    ],
    code: "web2200160-1",
    vendor: "Mỹ",

    status: "còn hàng | hết hàng",
    info: [
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
      {
        sizeBox: "",
        demension: "",
        discountPercent: "-67%",
        specificPrice: 59000,
        originalPrice: 123,
      },
    ],
    description: "",
  },
];
